spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/neon

  cloud:
    gateway:
      routes:
        - id: movies
          uri: http://localhost:8039
          predicates:
            - Path=/movies/**
        - id: users
          uri: http://localhost:8037
          predicates:
            - Path=/auth/**
