spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/neon

  cloud:
    gateway:
      routes:
        - id: reserved
          uri: http://localhost:8036
          predicates:
            - Path=/reserved/**
        - id: reserve
          uri: http://localhost:8036
          predicates:
            - Path=/reserve/**
        - id: users
          uri: http://localhost:8037
          predicates:
            - Path=/auth/**
        - id: movies
          uri: http://localhost:8039
          predicates:
            - Path=/movies/**
        - id: shows
          uri: http://localhost:8039
          predicates:
            - Path=/shows/**
        - id: seats
          uri: http://localhost:8039
          predicates:
            - Path=/seats/**
        - id: seats
          uri: http://localhost:8039
          predicates:
            - Path=/backoffice/fares/**
